[window]
padding = { x = 12, y = 12 }

[colors.primary]
background = "#14161B"
foreground = "#E1E2E7"

[font]
size = 12.0

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"

[font.bold]
family = "MonaspiceNe Nerd Font"
style = "Bold"

[font.italic]
family = "MonaspiceNe Nerd Font"
style = "Italic"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

