[window]
padding = { x = 12, y = 12 }
opacity = 0.9
dimensions = { columns = 140, lines = 40 }

[colors.primary]
background = "#14161B"
foreground = "#E1E2E7"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono  Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[scrolling]
# no of lines kept in scrollback history
history = 10000
# no of lines scrolled per mouse wheel scroll movement
multiplier = 3

[cursor]
# style options: "Block", "Underline", or "Beam"
style = { shape = "Block", blinking = "On" }

[selection]
# automatically save highlighted terminal selections to system clipboard
save_to_clipboard = true

[[keyboard.bindings]]
key = "Left" # left arrow
# key = "H" # H-key
mods = "Control"
chars = "\u001bb" # Jump word left

[[keyboard.bindings]]
key = "Right" # right arrow
# key = "L" # L-key
mods = "Control"
chars = "\u001bf" # Jump word right

