background_image /home/dru/Pictures/walls/wall2.jpg
# background_image /home/dru/Pictures/walls/ganyu-genshin-impact.jpg
# background_image /home/dru/Pictures/walls/mornye-dark.jpg
# background_image /home/dru/Pictures/walls/wwaves.jpg
background_image_layout cscaled
background_tint 0.995
# background_opacity 0.97
