# background_image /home/dru/Pictures/walls/yamatasula.png
# background_image /home/dru/Pictures/walls/ganyu-genshin-impact.jpg
# background_image /home/dru/Pictures/walls/riven.jpg
background_image /home/dru/Pictures/walls/wwaves.jpg
background_image_layout cscaled
background_tint 0.99
# background_opacity 0.97
