## name: Doom One (Emacs)
## author: Ghost (inspired by doom-themes)
## license: MIT
## blurb: Deep slate background with a sophisticated violet/blue accent palette.

#: The basic colors
foreground              #bbc2cf
# background              #282c34
background              #181c24
selection_foreground    #282c34
selection_background    #ae81ff

#: Cursor colors
cursor                  #51afef
cursor_text_color       #282c34

#: URL underline color when hovering with mouse
url_color               #46d9ff

#: kitty window border colors and terminal bell colors
active_border_color     #51afef
inactive_border_color   #3f444a
bell_border_color       #ecbe7b
visual_bell_color       none

#: Tab bar colors
active_tab_foreground   #282c34
active_tab_background   #51afef
inactive_tab_foreground #5b6268
inactive_tab_background #21242b
tab_bar_background      #1c1f24

#: The basic 16 colors

#: black (Grey / Bright Grey)
color0 #1c1f24
color8 #5b6268

#: red
color1 #ff6c6b
color9 #ff6c6b

#: green
color2  #98be65
color10 #98be65

#: yellow
color3  #ecbe7b
color11 #ecbe7b

#: blue
color4  #51afef
color12 #51afef

#: magenta
color5  #c678dd
color13 #c678dd

#: cyan
color6  #46d9ff
color14 #46d9ff

#: white
color7  #abb2bf
color15 #dfdfdf
